### ISSUE TITLE
XQ doesn't backfill all the way back

### ISSUE THREAD

**Issue by ConanMishler** [blocknetdx/XQuery#20]
Hmm, looks like XQ stopped backfill indexing Pegasys at block 38202:
```
% ./xq.py --xqbmin SYS --host $VPS4 --projectid b7855f76-48c8-415b-b1b4-2e0118ef15f5 --apikey QTFFhetkbdE2-Y4Zn7b_EtUFAVANhi8Yi1XC8Ce4Y2Y
🔀 XQuery for MIN blocknumber SYS
{'data': {'xquery': [{'xquery_blocknumber': 38202, 'xquery_timestamp': 0}]}}
```
I had instructed it to index all the way back to block 1 in `xquery.yaml`:
```yaml
  historical:
  - fromBlock: '1'
```
but it seems to be frozen/stuck at block 38202 (for 1 day now).

**Comment by pom11** [comment]
cause maybe Pegasys is not on older blocks?!

**Comment by ConanMishler** [comment]
> cause maybe Pegasys is not on older blocks?!

So according to the pegasys_Router abi, the Pegasus contract address seems to be: `0x017dAd2578372CAEE5c6CddfE35eEDB3728544C4`. Are you saying XQ won't index blocks prior to the block where the Pegasys Router contract was created (which might be block 38202)?  Here is the Pegasys Contract: https://explorer.syscoin.org/address/0x017dAd2578372CAEE5c6CddfE35eEDB3728544C4/transactions
I'm still trying to figure out how to find on which block it was created...

**Comment by ConanMishler** [comment]
Ah, I found where PegasysRouter contract was created:
https://explorer.syscoin.org/tx/0x7dfaa9b51d600eb7cbf71b6a14b13b6068da90a40d25b04022a429479f5037a0/internal-transactions
So that was at block 38190, just 12 blocks before XQ stopped backfilling at block 38202! So it does seem possible that the first transaction involving PegasysRouter didn't occur until block 38202! Thanks for the hint, @pom11 ! Best wishes in your new job!

**Comment by pom11** [comment]
thx @ConanMishler and good luck to you too! take care in your QAs and pay attention! i ll keep an eye over here!

**Comment by ConanMishler** [comment]
Closing this issue. It's confirmed; the first transaction involving the Pegasys Router contract doesn't happen until block 38202, so XQ is backfilling properly. 😊

**Comment by shrnkld** [comment]
<img width="1258" alt="Screen Shot 2022-04-20 at 17 48 14" src="https://user-images.githubusercontent.com/70695824/164432152-041d1c5d-22b8-4c73-97b5-a3661ccdbdfc.png">
