### ISSUE TITLE
Implement Redis cache

### ISSUE THREAD

**Issue by shrnkld** [blocknetdx/XQuery#22]
### To do:
- [ ] move in-memory cache from local to redis

**Comment by ConanMishler** [comment]
To clarify, this task includes not only creating a redis cache accessible by all XQuery event processor containers, but also removing the per-container cache in each event processor container.

**Comment by atcsecure** [comment]
1st task - use redis cache for timestamp

**Comment by atcsecure** [comment]
> To clarify, this task includes not only creating a redis cache accessible by all XQuery event processor containers, but also removing the per-container cache in each event processor container.

the redis cache will be handled by the auto-builder, it will be a container
